bigquery-profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: cisa-cve-data-pipeline
      dataset: dataset_final
      threads: 10 # Must be a value of 1 or greater
      keyfile: /app/secrets/cisa-elt-pipeline.json #Updated to match the path described in the Dockerfile when building the containers
      location: US
      job_retries: 2
      job_retry_deadline_seconds: 60
      